services:
  backend:
    build: .
    restart: on-failure
    container_name: fastapi_app
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:18.3
    restart: always
    container_name: fastapi_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}

volumes:
  postgres_data:
